[package]
name = "encrypt"
version = "0.1.0"
authors = ["simon lehericey <mail@simon.lehericey.net>"]
edition = "2018"
build = "build.rs" # Cargo only supports one build script per project at the moment

[dependencies]
sodiumoxide = "0.2.2"
futures = "0.3.1"
futures-core = "0.3.1"
actix-web = { version="2.0.0" }
actix-rt = "1"
bytes = "0.5.3"
docopt = "1"
serde = { version = "1", features = ["derive"] }
log = "0.4"
env_logger = "0.6"

[dev-dependencies]
rand = "0.6.5"
assert_cmd = "0.11"
assert_fs = "0.11"
proptest = "0.9.4"
